#!/bin/bash
DIR="$( cd "$( dirname "$0" )" && pwd )"

permission-link(){
  permission "$1" && mv "$1" "$1.bak" && ln -snf "$2" "$1"
}
permission(){
  if [[ -e "$1" && ! -L "$1" ]]; then
    echo -n "$1 already exits. Replace? [y/n] "
    read -s -n 1 key
    if [[ "$key" == "y" ]]; then
      echo OK
      return 0
    else
      echo skipping
      return 1
    fi
  fi
  return 1
}

for f in `ls "$DIR" | grep -Ev "setup|config"`; do
  permission-link "$HOME/.$f" "$DIR/$f"
done

for f in `ls "$DIR/config"`; do
  permission-link "$HOME/.config/$f" "$DIR/config/$f"
done

if [[ ! -L "$DIR/dotrc/location" ]]; then
  echo Go symlink your location in dotrc directory
fi

mkdir -p "$HOME/.scripts/data"
