#!/bin/bash

export SCALA_HOME="/opt/scala"
export PATH="$PATH:${SCALA_HOME}/bin:${JAVA_HOME}/bin"
export PATH=$PATH:/home/bene/.scripts:/home/bene/.bin:/home/bene/.scripts/spotify
export _JAVA_AWT_WM_NONREPARENTING=1

. ~/.bashrc_ri3k
