#!/bin/bash
CARD="-c 2"
if [[ $1 == mute ]]; then
 amixer -q $CARD set Master toggle
elif [[ $1 == ? ]]; then
 amixer get $CARD Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "MM" } else { print $2 }}' | head -n 1 
else
  pol=${1%%[0-9]*}
  val=${1##[+-]}

  amixer -q $CARD set Master "$val"dB"$pol"
fi

