#!/bin/bash
if [[ $1 == mute ]]; then
 amixer -q $SND_CARD_OPTS set Master toggle
elif [[ $1 == ? ]]; then
 amixer get $SND_CARD_OPTS Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "MM" } else { print $2 }}' | head -n 1 
else
  pol=${1%%[0-9]*}
  val=${1##[+-]}

  amixer -q $SND_CARD_OPTS set Master "$val"dB"$pol"
fi

