#!/bin/bash

stty -F /dev/ttyACM0 9600 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke min 1 time 5
cat /dev/ttyACM0 | grep --line-buffered "$"
