#!/bin/bash
depfile=/tmp/depfile
case $1 in
--init)
  [[ ! -d $2 ]] && echo "$2 not a directory" && exit
  mvn dependency:tree > $depfile;;
--help)
  echo "usage: depfind dependency"
  echo "       depfind --init directory";;
--list|-l)
  cat $depfile | grep INFO.*com.qatarlyst | sed -e s/^[^c]*com.qatarlyst:// -e 's/:\(compile\|test\)//' | sort -u;;
*)
  target=$1
  alldeps=$(cat $depfile | egrep "\+.*$target|Building" | grep "\+.*$target" -B1 --color )
  #topleveldeps=$(echo "$alldeps" | grep '[INFO]...-' -B1 | grep Building | sed -e 's/.*Building //' )
  #toplevelsedfilter=$(echo "$topleveldeps" | sed -e 's/ /:\.\{3,5}:/' -e 's/^/|/')
  #toplevelcount=$(echo $topleveldeps | wc -l)
  #sedfilter=$target$toplevelsedfilter
  echo "$alldeps" | grep --color -A1 Building.*

  #echo $sedfilter
  #cat $depfile | grep -Ef <(echo $sedfilter)
  #echo "$alldeps" | grep $1 -B$toplevelcount
esac
    
