#!/bin/bash

setxkbmap -option caps:hyper && xmodmap -e 'remove mod4 = Hyper_L' && xmodmap -e 'add mod3 = Hyper_L'; 
python -c 'from ctypes import *; X11 = cdll.LoadLibrary("libX11.so.6"); display = X11.XOpenDisplay(None); X11.XkbLockModifiers(display, c_uint(0x0100), c_uint(2), c_uint(0)); X11.XCloseDisplay(display)'    

