#!/bin/bash
set -e

HOWMANY=${1:-10}

function list(){
	git reflog -n10000 --pretty='%cr|%gs' --grep-reflog='checkout: moving' HEAD | {
		seen=":"
		git_dir="$(git rev-parse --git-dir)"
		while read line; do
			date="${line%%|*}"
			branch="${line##* }"
			if ! [[ $seen == *:"${branch}":* ]]; then
				seen="${seen}${branch}:"
				if [ -f "${git_dir}/refs/heads/${branch}" ]; then
					printf "%s\t%s\n" "$date" "$branch"
				fi
			fi
		done
	} | head -n $HOWMANY
}

function main(){
	list | fzf | cut -f2 | xargs git checkout
}

main

