#!/bin/bash

rm ~/dev/mule/apps/esb* -rf
cd ~/dev-projects/global-platform/trunk/esb
for file in `find -name *.zip`; do
  target=$(basename $file)
  cp $file ~/dev/mule/apps/${target%-[0-9]*}.zip
done

#(cd /tmp; mule)
