#!/bin/bash

filename=$1
linenum=$2
colnum=$3

function upsearch () {
    test / == "$PWD" && return || test -e "$1" && echo "found: " "$PWD" && return || cd .. && upsearch "$1"
}


if upsearch .idea; then
	/Users/ben/Library/Application\ Support/JetBrains/Toolbox/scripts/idea --line $linenum --column $colnum $filename
else
  open $filename
fi




