#!/bin/bash

file=`find ~/.m2/repository/com/qatarlyst -name $1`

base=`echo $1 | sed "s/-[0-9\.]*-SNAPSHOT.jar//"`

echo "-----" propagated `basename $file` ------
echo
for dep in `find $MULE_HOME/apps -name "*.jar" | grep "/$base"`; do
  cp $file $dep
  appdir=`echo $dep | sed "s/lib\/$base.*//"`
  conf=`echo $appdir | sed "s/.*apps//"`
  echo -n bounce `echo $appdir | grep -o "esb-.*" | tr "/" " "` "[y/n]"?
  read -s -n 1 key
  if [[ "$key" == "" ]] || [[ "$key" == "y" ]] || [[ "$key" == "Y" ]]; then
    touch "$appdir"mule-config.xml
    echo " BOUNCED"
  else
    echo " ignored"
  fi
done
