#!/bin/bash

FILE=;
PORT=9054


while [ ! $# -eq 0 ]
do
    echo $1
    case "$1" in
        -a)
            APPEND=1;
            ;;
        *)
            FILE="$1";
            ;;
    esac
    shift
done
    echo $APPEND


if [[ "$FILE" ]]; then
  FILE=`basename $FILE`
  FULLPATH=`readlink -f $FILE`

  if [ -f "$FULLPATH" ] || [ -d "$FULLPATH" ]; then
    if [ ! -d ~/.pythonserver ];then
      mkdir ~/.pythonserver
    fi

    
    cd ~/.pythonserver
    if [ ! $APPEND ]; then
      rm ~/.pythonserver/*
    fi
    ln -s $FULLPATH $FILE
  fi
fi

cd ~/.pythonserver

echo "http://$(myip):$PORT/$FILE" | clip

if [ ! `pgrep -f "python -m SimpleHTTPServer $PORT"` ]; then
  python -m SimpleHTTPServer $PORT &> /dev/null &
else
  echo Rehosted. Server still running somewhere.
fi

