#!/bin/bash


fix(){
  for i in `find "$1" -name "$2"`; do
    grep $3 $i && (\
      sed -i "/$3/d" $i;
      echo -e '\n'$3'=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.56.1)(PORT = 1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)))' >> $i;
    )
  done
}


fix $MULE_HOME/conf "*.properties" global_platform.db.url
fix $RI3K_DEV_ROOT/dev-env "*.properties" global_platform.db.url
fix $RI3K_DEV_ROOT/dev-env liquibase.properties global_platform_url
