#!/bin/bash
log=~/.scripts/data/locklog.txt
if [[ $1 ]]; then
  filter="[A-Z]\w{2} $1 "
else
  filter="Mon ... [0-9]*"
fi
day=$( tac $log | egrep -o "$filter" | head -n1 )
days=$( cat $log | egrep -o "([A-Z]\w{2} ){2}[0-9][0-9]? " | uniq )

hours(){
  #daystart=`echo $1 | sed "s/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/10:00:00/"`
  daystart=$1
  startseconds=`date --date "$daystart" "+%s"`
  endseconds=`date --date "$2" "+%s"`
  workseconds=$((endseconds - startseconds - 3600))
  date --date "Mon Jun 11 00:00:00 BST 2012 +$workseconds seconds" | egrep -o "([0-9]{2}:[0-9]{2})"
}

for i in `echo "$days" | grep -A4 "$day" | sed "s/ /./g"`; do 
  d=`echo "$i" | sed "s/\.$/ /"`
  found=`cat $log | grep -E "$d" | tail -1 | cut -c6-`
  starttime=`cat $log | grep -E "$d" | grep OUT | head -1 | cut -c6-`
  echo $found ------- `hours "$starttime" "$found"`
done
