#!/bin/bash
log=~/.scripts/data/locklog.txt
day=$( tac $log | egrep -o "[A-Z]\w{2} $1 " | head -n1 )
days=$( cat $log | egrep -o "([A-Z]\w{2} ){2}[0-9][0-9]? " | uniq )

hours(){
  daystart=`echo $1 | sed "s/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/10:00:00/"`
  startseconds=`date --date "$daystart" "+%s"`
  endseconds=`date --date "$1" "+%s"`
  workseconds=$((endseconds - startseconds))
  date --date "Mon Jun 11 00:00:00 BST 2012 +$workseconds seconds" | egrep -o "([0-9]{2}:[0-9]{2})"
}

for i in `echo "$days" | grep -A4 "$day" | sed "s/ /./g"`; do 
  d=`echo "$i" | sed "s/\.$/ /"`
  found=`cat $log | grep -E "$d" | tail -1 | cut -c6-`
  echo $found ------- `hours "$found"`
done
